import { getAppUrl } from "@/lib/app-url";
import { foodNameKey } from "@/lib/micronutrients/aggregate";
import type { MicronutrientValues } from "@/lib/rda";

/** Server-side lookup of ANSES-CIQUAL lab micronutrients by normalized food
 *  name, for the enrichment cron. CIQUAL is curated reference data, so for the
 *  generic foods it covers it's more reliable than OFF's crowd-sourced median
 *  or an AI estimate.
 *
 *  The data lives in `public/ciqual-micronutrients.json` (generated by
 *  scripts/build-ciqual.py — per-100g, already in each nutrient's canonical
 *  unit). Serverless functions don't ship `public/` on their filesystem, so we
 *  fetch the deployed asset once per process and cache the name→values map.
 *  Server-only — only the enrich-micronutrients cron imports it. */

type MicroRow = { name: string; micronutrients: MicronutrientValues };

let cache: Map<string, MicronutrientValues> | null = null;
let inflight: Promise<Map<string, MicronutrientValues>> | null = null;

function load(): Promise<Map<string, MicronutrientValues>> {
  if (cache) return Promise.resolve(cache);
  if (!inflight) {
    inflight = fetch(`${getAppUrl()}/ciqual-micronutrients.json`)
      .then((res) => (res.ok ? (res.json() as Promise<MicroRow[]>) : []))
      .then((rows) => {
        const map = new Map<string, MicronutrientValues>();
        for (const row of rows) {
          // Keyed by the same `foodNameKey` the enqueue path uses, so the cron's
          // name_key matches. First entry wins on a collision (rare — CIQUAL
          // names are specific).
          const key = foodNameKey(row.name);
          if (!map.has(key)) map.set(key, row.micronutrients);
        }
        cache = map;
        return map;
      })
      .catch(() => {
        inflight = null; // allow a retry on a later cron run
        return new Map<string, MicronutrientValues>();
      });
  }
  return inflight;
}

/** CIQUAL's per-100g micronutrients for a `foodNameKey`-normalized name, or
 *  `null` when CIQUAL has no matching row. Values are in each nutrient's
 *  canonical unit (matching `MicronutrientValues`). */
export async function ciqualMicronutrients(
  nameKey: string,
): Promise<MicronutrientValues | null> {
  const map = await load();
  return map.get(nameKey) ?? null;
}

/** Test seam: drop the in-memory cache. */
export function __resetCiqualMicrosForTests(): void {
  cache = null;
  inflight = null;
}
