import { getAppUrl } from "@/lib/app-url";
import { foodNameKey } from "@/lib/micronutrients/aggregate";
import type { MacroBreakdown } from "@maqro/core/types";

/** Server-side lookup of ANSES-CIQUAL per-100g MACRO-BREAKDOWN values
 *  (sugars, fiber, saturated/mono/poly fat) by normalized food name, for the
 *  enrichment cron's breakdown backfill — the macro twin of
 *  [ciqual-micros.ts](./ciqual-micros.ts).
 *
 *  Reads the SAME `public/ciqual-database.json` asset the food-search
 *  typeahead already fetches (generated by scripts/build-ciqual.py; the
 *  breakdown fields ride each Food row, per-100g in grams), so no new build
 *  artifact is needed. Fetched once per process and cached. Server-only. */

type CiqualFoodRow = { name: string } & MacroBreakdown;

const BREAKDOWN_KEYS = [
  "sugars",
  "fiber",
  "saturatedFat",
  "monoFat",
  "polyFat",
] as const;

let cache: Map<string, MacroBreakdown> | null = null;
let inflight: Promise<Map<string, MacroBreakdown>> | null = null;

function load(): Promise<Map<string, MacroBreakdown>> {
  if (cache) return Promise.resolve(cache);
  if (!inflight) {
    inflight = fetch(`${getAppUrl()}/ciqual-database.json`)
      .then((res) => (res.ok ? (res.json() as Promise<CiqualFoodRow[]>) : []))
      .then((rows) => {
        const map = new Map<string, MacroBreakdown>();
        for (const row of rows) {
          const out: MacroBreakdown = {};
          for (const key of BREAKDOWN_KEYS) {
            const v = row[key];
            if (typeof v === "number" && Number.isFinite(v)) out[key] = v;
          }
          if (Object.keys(out).length === 0) continue;
          // Same key + first-entry-wins convention as the micros map.
          const key = foodNameKey(row.name);
          if (!map.has(key)) map.set(key, out);
        }
        cache = map;
        return map;
      })
      .catch(() => {
        inflight = null; // allow a retry on a later cron run
        return new Map<string, MacroBreakdown>();
      });
  }
  return inflight;
}

/** CIQUAL's per-100g macro breakdown for a `foodNameKey`-normalized name,
 *  or `null` when CIQUAL has no row (or the row carries no breakdown). */
export async function ciqualBreakdown(
  nameKey: string,
): Promise<MacroBreakdown | null> {
  const map = await load();
  return map.get(nameKey) ?? null;
}

/** Test seam: drop the in-memory cache. */
export function __resetCiqualBreakdownForTests(): void {
  cache = null;
  inflight = null;
}
